###
GET http://localhost:3700/user/all 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM2ODc4OTcsImV4cCI6MTYyMzczMTA5N30.at_Xc_DHA9V3aXp98BvuFkjGOWye4KXUzkOf2keqZi0
###
POST http://localhost:3700/user/new
content-type: application/json

{
    "name": "test15",
    "email": "test15@asdf.com",
    "password": "123"
}

###
PUT http://localhost:3700/user/update/60c49158a92ab42ef4a6e72d
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1MTQ4MzIsImV4cCI6MTYyMzU1ODAzMn0.xdsRln2r2StpCjrVU0GEipzWlWoCJt4qrptUybLAskU

{
    "name": "Pedro",
    "email": "asdf@asdf.com",
    "password": "123",
    "google": true
}

###
DELETE http://localhost:3700/user/delete/60c49158a92ab42ef4a6e72d
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1MTQ4MzIsImV4cCI6MTYyMzU1ODAzMn0.xdsRln2r2StpCjrVU0GEipzWlWoCJt4qrptUybLAskU
#################################################################

POST http://localhost:3700/login/
content-type: application/json

{
    "email": "asdf@asdff.com",
    "password": "123"
}

#################################################################

###
GET http://localhost:3700/hospital/all 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM2ODc4OTcsImV4cCI6MTYyMzczMTA5N30.at_Xc_DHA9V3aXp98BvuFkjGOWye4KXUzkOf2keqZi0
###
POST http://localhost:3700/hospital/new
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0

{
    "name": "MRW"
}

###
PUT http://localhost:3700/hospital/update/60c5fce638382f44c4b740c7
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0

{
    "name": "MRW",
    "user": "60c4a03fb2bce5068ce31d77"
}

###
DELETE http://localhost:3700/hospital/delete/60c5fff29c8b8f3ad08b09a2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0

#################################################################

###
GET http://localhost:3700/doctor/all 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0
###
POST http://localhost:3700/doctor/new
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0

{
    "name": "De santos",
    "hospital" : "60c61f1df133a33cc448e894"
}

###
PUT http://localhost:3700/doctor/update/60c5fce638382f44c4b740c7
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0

{
    "name": "De santos",
    "user": "60c4a03fb2bce5068ce31d77"
}

###
DELETE http://localhost:3700/doctor/delete/60c5fff29c8b8f3ad08b09a2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0
###
GET http://localhost:3700/find/all/mr
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM1ODc4NjksImV4cCI6MTYyMzYzMTA2OX0.qcAKZeOCgMm1JmF5zaHxCsb0LF_1q-TqAT4frnhU2v0

###
GET http://localhost:3700/find/concrete/user/pablo
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM2ODc4OTcsImV4cCI6MTYyMzczMTA5N30.at_Xc_DHA9V3aXp98BvuFkjGOWye4KXUzkOf2keqZi0

###
PUT http://localhost:3700/upload/user/60c4a03fb2bce5068ce31d77
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MGM0YTAzZmIyYmNlNTA2OGNlMzFkNzciLCJpYXQiOjE2MjM2ODc4OTcsImV4cCI6MTYyMzczMTA5N30.at_Xc_DHA9V3aXp98BvuFkjGOWye4KXUzkOf2keqZi0